

#spring 配置
spring:
  profiles:
      active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.106.208.40:3306/tuboshi_cms
      password: 1234
      username: root
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1
        connection-init-sql: SELECT 1
        maximum-pool-size: 40
        minimum-idle: 10
  jpa:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
  application:
      name: "cms-${spring.profiles.active}-${dubbo.registry.group}-@project.version@"
  cloud:
      zookeeper:
          connect-string: ${dubbo.registry.address}
          discovery:
            preferIpAddress: true
            uri-spec: "{scheme}://{address}:{port}/${server.context-path}"

  redis:
      host: 39.106.208.40
      port: 6379
      password: 578519083

#基本信息
info:
  build:
    group:      @project.groupId@
    artifact:   @project.artifactId@
    version:    @project.version@

#关闭监控限制
management:
  security:
    enabled: false

#开启 ip 白名单
actuator.ip_white_list: localhost,127.0.0.1,0:0:0:0:0:0:0:1,39.106.208.40

#日志配置
logging:
  pattern:
    #console: "[${project.artifactId}] %d %p [%t] %C.%M[%L] | %m%n"
  level:


#dubbo 配置
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    protocol: zookeeper
    address: www.memory3334.com:2181
    group:
  protocol:
    port: -1
  consumer:
    retries: 0
    check: false
    version: 1.0.0
  provider:
    version: 1.0.0

server:
  context-path: /cms
  port: 8777

packet_enable: true


#oss
oss:
  bucketname:
    memory3334-bucket
  accessKeyId:
    LTAIROjhc5omNXHO
  accessKeySecret:
    ZsobZBj14WEROax4q0SbQ1q0drcvSz
  endpoint:
    oss-cn-shanghai.aliyuncs.com